on:
  push:
    branches:    
      - 'releases/**'

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-20.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
    # - name: Checkout repository
    #   uses: actions/checkout@v2
    #   with: 
    #     ref: ${{ github.event.push.head.sha }}
    # - name: Set up Python 3.9
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.9
    # - name: Install pypa/build
    #   run: >-
    #     python -m
    #     pip install
    #     build
    #     --user
    # - name: Build a binary wheel and a source tarball
    #   run: >-
    #     python -m
    #     build
    #     --sdist
    #     --wheel
    #     --outdir dist/
    #     .
